"""Disposable synthetic release material for the persistence corrective probes.

The gate forbids running real Resident B, revealing the real phase-B cursor, and
touching the sealed C15 fixture or the accepted A-003 evidence.  The kill/restart
probes still have to drive the *real* release operator module, so this file
generates a **disposable synthetic fixture + manifest** and loads the real,
unmodified v2 release operator and mechanical ingest adapter against it.

Nothing here reads, copies or derives from:

* ``reviews/internal_habitation/c15-rcc/v1/fixture/sealed_fixture.json``
* the accepted A-003 World / release state / cursor 14
* the retired RERUN-002 run, session or request identities

The synthetic cursor space is 1..N with N far below the real phase boundary, and
the synthetic fixture digest is a fresh SHA-256 over generated bytes.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from types import ModuleType
from typing import Any

SYNTHETIC_FIXTURE_VERSION = "c15-synthetic-disposable-fixture-v1"
SYNTHETIC_SCHEMA_VERSION = "c15-synthetic-event-v1"
SYNTHETIC_CONTRACT_VERSION = "c15-synthetic-sequential-release-v1"
SYNTHETIC_INGEST_ADAPTER_VERSION = "c15-synthetic-mechanical-ingest-v1"
SYNTHETIC_BINDING_VERSION = "c15-synthetic-event-binding-v1"
SYNTHETIC_CANONICAL_ADAPTER_VERSION = "c15-synthetic-canonical-adapter-v1"
SYNTHETIC_CANONICAL_BINDING_VERSION = "c15-synthetic-canonical-binding-v1"

SUBJECT_ID = "user_1"
PHASE_A_MAX = 24
PHASE_B_START = 25

VISIBLE_KEYS = (
    "event_id",
    "sequence",
    "occurred_at",
    "dimension",
    "source_kind",
    "source_class",
    "modality",
    "resident_visible_payload",
)


def _repo_root() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "src" / "aios_core").is_dir() and (parent / "reviews").is_dir():
            return parent
    raise RuntimeError("repository root not found")


REPO_ROOT = _repo_root()
V2_RELEASE = REPO_ROOT / "reviews" / "internal_habitation" / "c14-resident" / "v2" / "release"


def _load(name: str, path: Path) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise RuntimeError(f"cannot load frozen release module: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def build_fixture(*, event_count: int = 30, seed: str = "c15-synthetic") -> dict[str, Any]:
    """Generate a disposable synthetic fixture with the real operator's shape."""
    if not 30 <= event_count <= 40:
        raise ValueError("synthetic fixture must hold 30..40 events (operator contract)")
    if event_count <= PHASE_B_START:
        raise ValueError("synthetic fixture must include a phase-B tail")
    events: list[dict[str, Any]] = []
    base = datetime(2026, 9, 27, 0, 0, tzinfo=timezone.utc)
    for index in range(1, event_count + 1):
        phase = "A" if index <= PHASE_A_MAX else "B"
        digest = hashlib.sha256(f"{seed}:{index}".encode()).hexdigest()[:12]
        if phase == "A":
            payload = f"[synthetic] observation {index} ({digest}) - no real resident content"
            source_class = "SENSOR" if index % 2 else "PLATFORM"
            source_kind = "sensor" if index % 2 else "platform"
            modality = "text"
            dimension = "dim:observation"
        else:
            payload = f"[synthetic] conversation turn {index} ({digest}) - no real resident content"
            source_class = "USER"
            source_kind = "conversation"
            modality = "text"
            dimension = "dim:conversation"
        events.append(
            {
                "event_id": f"synthetic-evt-{index:04d}",
                "sequence": index,
                "phase": phase,
                "occurred_at": (base + timedelta(minutes=index)).isoformat(),
                "dimension": dimension,
                "source_kind": source_kind,
                "source_class": source_class,
                "modality": modality,
                "resident_visible_payload": payload,
            }
        )
    return {
        "fixture_version": SYNTHETIC_FIXTURE_VERSION,
        "supersedes_fixture_version": "c15-synthetic-none",
        "schema_version": SYNTHETIC_SCHEMA_VERSION,
        "release_contract_version": SYNTHETIC_CONTRACT_VERSION,
        "timezone": "UTC",
        "subject_id": SUBJECT_ID,
        "events": events,
    }


def write_bundle(root: Path, fixture: dict[str, Any]) -> tuple[Path, Path, dict[str, Any]]:
    fixture_path = root / "synthetic_fixture.json"
    manifest_path = root / "synthetic_fixture_manifest.json"
    raw = json.dumps(fixture, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    fixture_path.write_text(raw, encoding="utf-8")
    digest = "sha256:" + hashlib.sha256(raw.encode("utf-8")).hexdigest()
    manifest = {
        "fixture_version": SYNTHETIC_FIXTURE_VERSION,
        "schema_version": SYNTHETIC_SCHEMA_VERSION,
        "release_contract_version": SYNTHETIC_CONTRACT_VERSION,
        "release_operator_version": "c15-synthetic-operator-v1",
        "ingest_adapter_version": SYNTHETIC_INGEST_ADAPTER_VERSION,
        "fixture_binding_version": SYNTHETIC_BINDING_VERSION,
        "canonical_conversation_adapter_version": SYNTHETIC_CANONICAL_ADAPTER_VERSION,
        "canonical_conversation_binding_version": SYNTHETIC_CANONICAL_BINDING_VERSION,
        "subject_id": SUBJECT_ID,
        "fixture_sha256": digest,
        "event_count": len(fixture["events"]),
        "phase_a_count": sum(1 for e in fixture["events"] if e["phase"] == "A"),
        "phase_b_count": sum(1 for e in fixture["events"] if e["phase"] == "B"),
        "handoff": {
            "phase_a_final_cursor": PHASE_A_MAX,
            "phase_b_first_cursor": PHASE_B_START,
        },
        "generated_at_epoch": time.time(),
        "note": "disposable synthetic material; not the sealed C15 fixture",
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return fixture_path, manifest_path, manifest


class SyntheticRelease:
    """Real release operator + mechanical ingest adapter bound to synthetic bytes."""

    def __init__(self, root: Path, *, event_count: int = 30, seed: str = "c15-synthetic") -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)
        fixture = build_fixture(event_count=event_count, seed=seed)
        self.fixture_path, self.manifest_path, self.manifest = write_bundle(self.root, fixture)
        self.fixture = fixture
        self.events = fixture["events"]

        # Load the FROZEN, UNMODIFIED release operator and ingest adapter, then
        # point their module-level constants at the synthetic bundle.  No source
        # file in reviews/** or src/aios_core/** is edited.
        self.operator = _load("c15_synth_release_operator", V2_RELEASE / "release_operator.py")
        self.adapter = _load("c15_synth_mechanical_adapter", V2_RELEASE / "mechanical_ingest_adapter.py")

        sha = self.manifest["fixture_sha256"]
        for module in (self.operator, self.adapter):
            module.FIXTURE_VERSION = SYNTHETIC_FIXTURE_VERSION
            module.FIXTURE_SHA256 = sha
            module.SCHEMA_VERSION = SYNTHETIC_SCHEMA_VERSION
            module.CONTRACT_VERSION = SYNTHETIC_CONTRACT_VERSION
            module.BINDING_VERSION = SYNTHETIC_BINDING_VERSION
            module.MANIFEST_PATH = self.manifest_path
            module.SUBJECT_ID = SUBJECT_ID
        self.operator.STATE_VERSION = "c15-synthetic-release-state-v1"
        self.operator.OPERATOR_VERSION = "c15-synthetic-operator-v1"
        self.operator.LEGACY_HANDOFF_OPERATOR_VERSION = "__c15_synthetic_no_legacy__"
        self.operator.INGEST_ADAPTER_VERSION = SYNTHETIC_INGEST_ADAPTER_VERSION
        self.operator.CANONICAL_CONVERSATION_ADAPTER_VERSION = SYNTHETIC_CANONICAL_ADAPTER_VERSION
        self.operator.CANONICAL_CONVERSATION_BINDING_VERSION = SYNTHETIC_CANONICAL_BINDING_VERSION
        self.operator.FIXTURE_PATH = self.fixture_path
        self.operator.PHASE_A_MAX = PHASE_A_MAX
        self.operator.PHASE_B_START = PHASE_B_START
        self.adapter.INGEST_ADAPTER_VERSION = SYNTHETIC_INGEST_ADAPTER_VERSION

    # ------------------------------------------------------------- operator

    def init_state(self, state_path: Path) -> dict[str, Any]:
        return self._run(self.operator.cmd_init, state=str(state_path), phase="A")

    def reveal(self, state_path: Path) -> dict[str, Any]:
        return self._run(self.operator.cmd_reveal, state=str(state_path), phase="A")

    def ack(
        self,
        state_path: Path,
        *,
        world_db: Path,
        sequence: int,
        event_id: str,
        ingest_ref: str,
    ) -> dict[str, Any]:
        return self._run(
            self.operator.cmd_ack,
            state=str(state_path),
            phase="A",
            world_db=str(world_db),
            sequence=sequence,
            event_id=event_id,
            ingest_ref=ingest_ref,
            conversation_session_id=None,
            conversation_turn_index=None,
        )

    def _run(self, command, **kwargs: Any) -> dict[str, Any]:
        import io
        from contextlib import redirect_stdout

        namespace = SimpleArgs(**kwargs)
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            command(namespace)
        return json.loads(buffer.getvalue().strip().splitlines()[-1])

    # --------------------------------------------------------------- ingest

    def ingest(self, world_db: Path, projection: dict[str, Any]) -> dict[str, Any]:
        return self.adapter.ingest_projection(world_db, projection, subject_id=SUBJECT_ID)


class SimpleArgs:
    def __init__(self, **kwargs: Any) -> None:
        self.__dict__.update(kwargs)
