"""Shared harness for the frozen K1-K5 kill/restart convergence probes.

Frozen before first execution
-----------------------------
The probe enumeration lives in ``PROBE_MANIFEST.json`` next to this file and is
hashed in ``PROBE_MANIFEST.sha256``.  The manifest is generated by::

    python tools/c15_persistence/freeze_probe_manifest.py

and is committed **before** the probes are first executed.  Changing the probe
code or the expected outcomes and re-running the same revision is forbidden; a
harness bug requires a new revision with its own manifest and hash.

Every probe follows the same shape:

1. create a disposable run under the authoritative backend path;
2. run the operator loop as a child process that SIGKILLs itself at the frozen
   kill barrier;
3. assert the child died with SIGKILL (exit ``-9``);
4. resume in a **fresh process** with no inherited memory;
5. compare the observed counters against a *freshly measured* uninterrupted
   baseline for the same environment.

The baseline is measured, never assumed: the gates are expressed as relations to
the baseline (no more than, exactly equal to), not as magic numbers.
"""

from __future__ import annotations

import json
import os
import shutil
import signal
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
RUNS_ROOT = Path(os.environ.get("C15_PERSISTENCE_RUNS_ROOT", "/home/user/c15-persistence-runs"))
PY = sys.executable


def repo_python_env() -> dict[str, str]:
    env = dict(os.environ)
    pythonpath = [str(REPO_ROOT / "src"), str(REPO_ROOT)]
    existing = env.get("PYTHONPATH")
    if existing:
        pythonpath.append(existing)
    env["PYTHONPATH"] = os.pathsep.join(pythonpath)
    env.setdefault("PYTHONDONTWRITEBYTECODE", "1")
    return env


def new_root(label: str) -> Path:
    """Fresh disposable run root under the authoritative backend path."""
    RUNS_ROOT.mkdir(parents=True, exist_ok=True)
    root = RUNS_ROOT / f"probe-{label}-{uuid.uuid4().hex[:12]}"
    root.mkdir(mode=0o700)
    return root


def wipe(root: Path) -> None:
    """Remove a run root (sealed generations are read-only)."""
    if not root.exists():
        return
    for path in sorted(root.rglob("*"), key=lambda p: len(p.parts), reverse=True):
        try:
            if path.is_dir() and not path.is_symlink():
                path.chmod(0o700)
            elif path.is_file() and not path.is_symlink():
                path.chmod(0o600)
        except OSError:
            pass
    shutil.rmtree(root, ignore_errors=True)


def run_clip(root: Path, run_id: str, session_id: str, args: list[str]) -> subprocess.CompletedProcess:
    cmd = [
        PY,
        "-m",
        "tools.c15_persistence.probe_cli",
        "--root",
        str(root / "backend"),
        "--run-id",
        run_id,
        "--session-id",
        session_id,
        *args,
    ]
    return subprocess.run(
        cmd,
        cwd=str(REPO_ROOT),
        env=repo_python_env(),
        capture_output=True,
        text=True,
        timeout=600,
    )


def parse(completed: subprocess.CompletedProcess) -> dict[str, Any]:
    if completed.returncode != 0:
        raise AssertionError(
            "probe command failed\n"
            f"returncode={completed.returncode}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        )
    return json.loads(completed.stdout)


def measure_baseline() -> dict[str, Any]:
    """Uninterrupted reference run: the only legitimate comparison point."""
    root = new_root("baseline")
    run_id = f"synthetic-run-baseline-{uuid.uuid4().hex[:8]}"
    session_id = f"synthetic-session-baseline-{uuid.uuid4().hex[:8]}"
    try:
        completed = run_clip(root, run_id, session_id, ["--mode", "create"])
        outcome = parse(completed)
    finally:
        wipe(root)
    observed = outcome["observed"]
    return {
        "reveals": observed["counters"].get("reveals", 0),
        "ingests": observed["counters"].get("ingests", 0),
        "acks": observed["counters"].get("acks", 0),
        "turns_completed": observed["counters"].get("turns_completed", 0),
        "capability_side_effects": observed["counters"].get("capability_side_effects", 0),
        "dispatch_ledger": len(observed["dispatch_ledger"]),
        "metering_rows": observed["metering_rows"],
        "assistant_outputs": observed["observation_counts"]["assistant_outputs"],
        "observations_for_event": observed["observation_counts"]["observations_for_event"],
        "generations": len(observed["generations"]),
    }


def run_kill_point(kill_point: str) -> dict[str, Any]:
    """Kill at ``kill_point``, resume in a fresh process, return observations."""
    root = new_root(kill_point.lower())
    run_id = f"synthetic-run-{kill_point.lower()}-{uuid.uuid4().hex[:8]}"
    session_id = f"synthetic-session-{kill_point.lower()}-{uuid.uuid4().hex[:8]}"
    try:
        killed = run_clip(
            root,
            run_id,
            session_id,
            ["--mode", "create", "--kill-at", kill_point],
        )
        if killed.returncode != -signal.SIGKILL:
            raise AssertionError(
                f"{kill_point}: child did not die at the kill barrier "
                f"(returncode={killed.returncode}, expected {-signal.SIGKILL})\n"
                f"stderr:\n{killed.stderr}"
            )
        resumed = run_clip(root, run_id, session_id, ["--mode", "resume"])
        outcome = parse(resumed)
    finally:
        wipe(root)
    return outcome


def observed_counters(outcome: dict[str, Any]) -> dict[str, Any]:
    """Counters measured *after* the crash + resume pair."""
    observed = outcome["observed"]
    return {
        "reveals": observed["counters"].get("reveals", 0),
        "ingests": observed["counters"].get("ingests", 0),
        "acks": observed["counters"].get("acks", 0),
        "turns_completed": observed["counters"].get("turns_completed", 0),
        "capability_side_effects": observed["counters"].get("capability_side_effects", 0),
        "dispatch_ledger": len(observed["dispatch_ledger"]),
        "metering_rows": observed["metering_rows"],
        "assistant_outputs": observed["observation_counts"]["assistant_outputs"],
        "observations_for_event": observed["observation_counts"]["observations_for_event"],
        "generations": len(observed["generations"]),
    }


def assert_convergence(
    kill_point: str,
    outcome: dict[str, Any],
    baseline: dict[str, Any],
) -> dict[str, Any]:
    """The frozen convergence invariant for one kill point.

    Recovery must converge to the same durable cursor without:

    * a second reveal;
    * a duplicate ingest;
    * a duplicate semantic decision (provider request/round);
    * a duplicate capability side effect;
    * a duplicate assistant output;
    * duplicate metering;
    * a duplicate ACK;
    * a skipped cursor.

    A terminal or ``in_doubt`` outcome is never accepted as convergence.
    """
    counters = observed_counters(outcome)
    ack = outcome["ack"]

    problems: list[str] = []

    # -- cursor actually advanced exactly once -------------------------------
    if ack.get("status") != "acked":
        problems.append(f"cursor was not acked: {ack!r}")
    if ack.get("sequence") != outcome["projection"]["sequence"]:
        problems.append("acked sequence is not the revealed cursor")
    if ack.get("event_id") != outcome["projection"]["event_id"]:
        problems.append("acked event id is not the revealed cursor")
    if counters["acks"] != baseline["acks"]:
        problems.append(f"ack count {counters['acks']} != baseline {baseline['acks']}")

    # -- no duplicate reveal / ingest ---------------------------------------
    if counters["reveals"] != baseline["reveals"]:
        problems.append(f"reveal count {counters['reveals']} != baseline {baseline['reveals']}")
    if counters["ingests"] != baseline["ingests"]:
        problems.append(f"ingest count {counters['ingests']} != baseline {baseline['ingests']}")
    if counters["observations_for_event"] != baseline["observations_for_event"]:
        problems.append(
            "durable observation count for the event changed: "
            f"{counters['observations_for_event']} != baseline {baseline['observations_for_event']}"
        )

    # -- no duplicate provider dispatch / semantic decision ------------------
    if counters["dispatch_ledger"] > baseline["dispatch_ledger"]:
        problems.append(
            f"provider dispatch count {counters['dispatch_ledger']} exceeds baseline "
            f"{baseline['dispatch_ledger']} (redispath)"
        )
    if counters["dispatch_ledger"] < baseline["dispatch_ledger"]:
        problems.append(
            f"provider dispatch count {counters['dispatch_ledger']} below baseline "
            f"{baseline['dispatch_ledger']} (skipped work)"
        )

    # -- no duplicate capability / output / metering -------------------------
    if counters["capability_side_effects"] > baseline["capability_side_effects"]:
        problems.append(
            f"capability side effects {counters['capability_side_effects']} exceed baseline "
            f"{baseline['capability_side_effects']}"
        )
    if counters["capability_side_effects"] < baseline["capability_side_effects"]:
        problems.append("capability work was skipped")
    if counters["assistant_outputs"] != baseline["assistant_outputs"]:
        problems.append(
            f"assistant outputs {counters['assistant_outputs']} != baseline "
            f"{baseline['assistant_outputs']}"
        )
    if counters["metering_rows"] != baseline["metering_rows"]:
        problems.append(
            f"metering rows {counters['metering_rows']} != baseline {baseline['metering_rows']}"
        )
    if counters["turns_completed"] != baseline["turns_completed"]:
        problems.append(
            f"turn completions {counters['turns_completed']} != baseline {baseline['turns_completed']}"
        )

    # -- no terminal / in_doubt left behind ----------------------------------
    disposition = outcome.get("turn", {}).get("recovery_actions") or []
    terminal = [
        action
        for action in disposition
        if action.get("action") in {"no_core_receipt", "authorize_skipped"}
    ]
    if terminal:
        problems.append(f"recovery left a non-converged action: {terminal}")

    if problems:
        raise AssertionError(
            f"{kill_point} CONVERGENCE FAILED:\n  - " + "\n  - ".join(problems)
        )
    return counters
